import streamlit as st
import requests
from PIL import Image
import os

# --- Configuration ---
API_URL = "http://localhost:8000/predict_image"
DRIFT_REPORT_PATH = "../drift_report.html"  # Path to the HTML file generated by your script
GRAFANA_URL = "http://localhost:3000"

st.set_page_config(
    page_title="Leukemia Detection & Monitoring",
    page_icon="🩸",
    layout="wide"
)

# --- Sidebar ---
st.sidebar.title("MLOps Dashboard")
app_mode = st.sidebar.selectbox("Choose Mode", ["Live Prediction", "Drift Report", "System Health"])

# --- MODE 1: LIVE PREDICTION ---
if app_mode == "Live Prediction":
    st.title("🩸 Leukemia Classification")
    st.markdown("Upload a blood cell image to classify it as **Benign (HEM)** or **Malignant (ALL)**.")

    uploaded_file = st.file_uploader("Choose an image...", type=["jpg", "png", "jpeg", "bmp"])

    if uploaded_file is not None:
        # 1. Show the image
        col1, col2 = st.columns(2)
        with col1:
            image = Image.open(uploaded_file)
            st.image(image, caption='Uploaded Image', use_column_width=True)

        # 2. Button to Predict
        if st.button("Analyze Cell"):
            with st.spinner('Sending to Neural Network (DenseNet121)...'):
                try:
                    # Prepare file for API
                    # We need to reset the pointer because st.image read it already
                    uploaded_file.seek(0)
                    files = {"file": (uploaded_file.name, uploaded_file, uploaded_file.type)}
                    
                    # Call the FastAPI backend
                    response = requests.post(API_URL, files=files)
                    
                    if response.status_code == 200:
                        result = response.json()
                        prediction = result.get("class", "Unknown")
                        confidence = result.get("confidence", 0.0)

                        # Display Results
                        with col2:
                            st.subheader("Analysis Result")
                            
                            # Color coding
                            if prediction.lower() == "all" or "malignant" in prediction.lower():
                                st.error(f"**Prediction:** {prediction}")
                            else:
                                st.success(f"**Prediction:** {prediction}")
                            
                            st.metric("Model Confidence", f"{confidence:.4f}")
                            
                            st.info("✅ Result logged to Qdrant Vector DB")
                    else:
                        st.error(f"Error from API: {response.text}")
                        
                except Exception as e:
                    st.error(f"Connection Failed: Is the API running? {e}")

# --- MODE 2: DRIFT REPORT ---
elif app_mode == "Drift Report":
    st.title("📉 Data Drift Analysis (Evidently AI)")
    
    if os.path.exists(DRIFT_REPORT_PATH):
        # Read the HTML file
        with open(DRIFT_REPORT_PATH, 'r', encoding='utf-8') as f:
            html_content = f.read()
        
        # Embed it in the page
        st.components.v1.html(html_content, height=1000, scrolling=True)
        
        st.success(f"Loaded report from: {os.path.abspath(DRIFT_REPORT_PATH)}")
    else:
        st.warning("⚠️ No Drift Report found.")
        st.info("Run `python generate_report.py` to generate the latest statistics.")

# --- MODE 3: SYSTEM HEALTH ---
elif app_mode == "System Health":
    st.title("🩺 MLOps System Monitor")
    
    col1, col2 = st.columns(2)
    
    with col1:
        st.subheader("Prometheus (Metrics)")
        st.markdown(f"[Open Prometheus Dashboard]({GRAFANA_URL})")
        st.image("https://prometheus.io/assets/onboarding/prometheus_logo_grey.svg", width=100)
        st.caption("Scrapes raw metrics from the API every 5 seconds.")

    with col2:
        st.subheader("Grafana (Visualization)")
        st.markdown(f"[Open Grafana Dashboard]({GRAFANA_URL})")
        st.image("https://upload.wikimedia.org/wikipedia/commons/3/3b/Grafana_icon.svg", width=100)
        st.caption("Visualizes Drift Scores and API Latency.")